//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.15 at 01:54:55 PM MEZ 
//
// Based on the XML schmema: TigerXML.xsd
// Reference: http://www.coli.uni-saarland.de/projects/salsa/
//


package tigerxml;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="subcorpus" type="{}subcorpusType"/>
 *         &lt;element name="s" type="{}sentenceType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyType", propOrder = {
    "subcorpusOrS"
})
public class Body {

    @XmlElements({
        @XmlElement(name = "s", type = Sentence.class),
        @XmlElement(name = "subcorpus", type = Subcorpus.class)
    })
    protected List<CorpusUnit> subcorpusOrS = new ArrayList<CorpusUnit>();

    /**
     * Gets the value of the subcorpusOrS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subcorpusOrS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubcorpusOrS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sentence }
     * {@link Subcorpus }
     * 
     * 
     */
    public List<CorpusUnit> getSubcorpusOrS() {
        return subcorpusOrS;
    }

	/**
	 * 
	 * @return Recursively collected sentences from corpus and all contained subcorpora.
	 */
    public List<CorpusUnit> getSentences() {
		Subcorpus wrappedSentences  = wrapCorpusUnitsInSubcorpus();
		return wrappedSentences.getSentences();
	}

	private Subcorpus wrapCorpusUnitsInSubcorpus() {
		Subcorpus result = new Subcorpus();
		result.getSubcorpusOrS().addAll(subcorpusOrS);
		return result;
	}

	public void addSentence(Sentence sentence) {
		subcorpusOrS.add(sentence);
	}
	
	/**
	 * Sets the corpus' body content.
	 */
	public void setSubcorpus(Subcorpus subcorpus) {
		subcorpusOrS = Collections.singletonList((CorpusUnit) subcorpus);
	}
}
