//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.15 at 01:54:55 PM MEZ 
//


package tigerxml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * model.TigerXml.xjc package. 
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema
 * type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Subcorpus_QNAME = new QName("", "subcorpus");
    private final static QName _Head_QNAME = new QName("", "head");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.TigerXml.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatchType() {
        return new Match();
    }

    /**
     * Create an instance of {@link Featurevalue }
     * 
     */
    public Featurevalue createFeaturevalueType() {
        return new Featurevalue();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHeadType() {
        return new Head();
    }

    /**
     * Create an instance of {@link Nonterminals }
     * 
     */
    public Nonterminals createNonterminalsType() {
        return new Nonterminals();
    }

    /**
     * Create an instance of {@link Matches }
     * 
     */
    public Matches createMatchesType() {
        return new Matches();
    }

    /**
     * Create an instance of {@link T }
     * 
     */
    public T createTType() {
        return new T();
    }

    /**
     * Create an instance of {@link Nt }
     * 
     */
    public Nt createNtType() {
        return new Nt();
    }

    /**
     * Create an instance of {@link Edge }
     * 
     */
    public Edge createEdgeType() {
        return new Edge();
    }

    /**
     * Create an instance of {@link Terminals }
     * 
     */
    public Terminals createTerminalsType() {
        return new Terminals();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeatureType() {
        return new Feature();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotationType() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVarType() {
        return new Var();
    }

    /**
     * Create an instance of {@link Edgelabel }
     * 
     */
    public Edgelabel createEdgelabelType() {
        return new Edgelabel();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBodyType() {
        return new Body();
    }

    /**
     * Create an instance of {@link Corpus }
     * 
     */
    public Corpus createCorpus() {
        return new Corpus();
    }

    /**
     * Create an instance of {@link Sentence }
     * 
     */
    public Sentence createSentenceType() {
        return new Sentence();
    }

    /**
     * Create an instance of {@link Subcorpus }
     * 
     */
    public Subcorpus createSubcorpusType() {
        return new Subcorpus();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMetaType() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Secedge }
     * 
     */
    public Secedge createSecedgeType() {
        return new Secedge();
    }

    /**
     * Create an instance of {@link Graph }
     * 
     */
    public Graph createGraphType() {
        return new Graph();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Subcorpus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subcorpus")
    public JAXBElement<Subcorpus> createSubcorpus(Subcorpus value) {
        return new JAXBElement<Subcorpus>(_Subcorpus_QNAME, Subcorpus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Head }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "head")
    public JAXBElement<Head> createHead(Head value) {
        return new JAXBElement<Head>(_Head_QNAME, Head.class, null, value);
    }

}
