//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.15 at 01:54:55 PM MEZ 
//
// Based on the XML schmema: TigerXMLHeader.xsd
// Reference: http://www.coli.uni-saarland.de/projects/salsa/
//


package tigerxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for annotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="annotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="feature" type="{}featureType" maxOccurs="unbounded"/>
 *         &lt;element name="edgelabel" type="{}edgelabelType" minOccurs="0"/>
 *         &lt;element name="secedgelabel" type="{}edgelabelType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "annotationType", propOrder = {
    "feature",
    "edgelabel",
    "secedgelabel"
})
public class Annotation {

    @XmlElement(required = true)
    protected List<Feature> feature;
    protected Edgelabel edgelabel;
    protected Edgelabel secedgelabel;

    /**
     * Gets the value of the feature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Feature }
     * 
     * 
     */
    public List<Feature> getFeature() {
        if (feature == null) {
            feature = new ArrayList<Feature>();
        }
        return this.feature;
    }

    /**
     * Gets the value of the edgelabel property.
     * 
     * @return
     *     possible object is
     *     {@link Edgelabel }
     *     
     */
    public Edgelabel getEdgelabel() {
        return edgelabel;
    }

    /**
     * Sets the value of the edgelabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Edgelabel }
     *     
     */
    public void setEdgelabel(Edgelabel value) {
        this.edgelabel = value;
    }

    /**
     * Gets the value of the secedgelabel property.
     * 
     * @return
     *     possible object is
     *     {@link Edgelabel }
     *     
     */
    public Edgelabel getSecedgelabel() {
        return secedgelabel;
    }

    /**
     * Sets the value of the secedgelabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Edgelabel }
     *     
     */
    public void setSecedgelabel(Edgelabel value) {
        this.secedgelabel = value;
    }

}
