//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.15 at 01:54:55 PM MEZ 
//
// Based on the XML schmema: TigerXMLSubcorpus.xsd
// Reference: http://www.coli.uni-saarland.de/projects/salsa/
//


package tigerxml;

import java.util.*;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for subcorpusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subcorpusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="subcorpus" type="{}subcorpusType"/>
 *         &lt;element name="s" type="{}sentenceType"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="external" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subcorpusType", propOrder = {
    "subcorpusOrS"
})
@XmlRootElement(name = "subcorpus")
public class Subcorpus implements CorpusUnit {

    @XmlElements({
        @XmlElement(name = "s", type = Sentence.class),
        @XmlElement(name = "subcorpus", type = Subcorpus.class)
    })
    protected List<CorpusUnit> subcorpusOrS;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String external;

    /**
     * Gets the value of the subcorpusOrS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subcorpusOrS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubcorpusOrS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sentence }
     * {@link Subcorpus }
     * 
     * 
     */
    public List<CorpusUnit> getSubcorpusOrS() {
        if (subcorpusOrS == null) {
            subcorpusOrS = new ArrayList<CorpusUnit>();
        }
        return this.subcorpusOrS;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the external property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternal() {
        return external;
    }

    /**
     * Sets the value of the external property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternal(String value) {
        this.external = value;
    }

	@Override
	public List<CorpusUnit> getSentences() {
		List<CorpusUnit> result = new LinkedList<CorpusUnit>();
		for (CorpusUnit cu : subcorpusOrS) {
			result.addAll(cu.getSentences());
		}
		return result;
	}

}
