//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.21 at 08:20:56 AM MESZ 
//
// Based on the XML schmema: corpusV1_1.xsd
// Reference: http://framenet.icsi.berkeley.edu
//

package framenet.corpus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "layers"
})
@XmlRootElement(name = "annotationSet")
public class AnnotationSet {

    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String status;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String frameName;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String frameRef;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lexUnitRef;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String luName;
    protected Layers layers;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the frameName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameName() {
        return frameName;
    }

    /**
     * Sets the value of the frameName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameName(String value) {
        this.frameName = value;
    }

    /**
     * Gets the value of the frameRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameRef() {
        return frameRef;
    }

    /**
     * Sets the value of the frameRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameRef(String value) {
        this.frameRef = value;
    }

    /**
     * Gets the value of the lexUnitRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLexUnitRef() {
        return lexUnitRef;
    }

    /**
     * Sets the value of the lexUnitRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLexUnitRef(String value) {
        this.lexUnitRef = value;
    }

    /**
     * Gets the value of the luName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLuName() {
        return luName;
    }

    /**
     * Sets the value of the luName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLuName(String value) {
        this.luName = value;
    }

    /**
     * Gets the value of the layers property.
     * 
     * @return
     *     possible object is
     *     {@link Layers }
     *     
     */
    public Layers getLayers() {
    	if (layers == null) {
    		layers = new Layers();
    	}
        return layers;
    }

    /**
     * Sets the value of the layers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Layers }
     *     
     */
    public void setLayers(Layers value) {
        this.layers = value;
    }

    public void addLayer(Layer layer) {
    	this.getLayers().getLayer().add(layer);
    }
}
