//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.21 at 08:20:56 AM MESZ 
//
// Based on the XML schmema: corpusV1_1.xsd
// Reference: http://framenet.icsi.berkeley.edu
//


package framenet.corpus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "text",
    "annotationSets"
})
@XmlRootElement(name = "sentence")
public class Sentence {

    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlElement(required = true)
    protected String text;
    @XmlElement(required = true)
    protected AnnotationSets annotationSets;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the annotationSets property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationSets }
     *     
     */
    public AnnotationSets getAnnotationSets() {
    	if (annotationSets == null) {
    		annotationSets = new AnnotationSets();
    	}
        return annotationSets;
    }

    /**
     * Sets the value of the annotationSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationSets }
     *     
     */
    public void setAnnotationSets(AnnotationSets value) {
        this.annotationSets = value;
    }

    public void addAnnotationSet(AnnotationSet annotationSet) {
    	this.getAnnotationSets().getAnnotationSet().add(annotationSet);
    }
}
